[wokwi]
version = 1
elf = "target/xtensa-esp32-espidf/release/rust-sport-tracker.bin"
firmware = "target/xtensa-esp32-espidf/release/rust-sport-tracker.bin"

[[chip]]
name = "at-modem"
binary = "chips/at-modem.chip.wasm"
